-- migration: initial_schema
-- purpose: create core tables for 10xcards mvp application
-- affected tables: flashcards, flashcard_generations, generation_error_logs
-- dependencies: supabase auth (auth.users table)
-- special considerations: 
--   - users table is managed by supabase auth
--   - rls policies ensure users can only access their own data
--   - includes trigger for auto-updating updated_at timestamp

-- =============================================================================
-- table: flashcard_generations
-- purpose: logs ai flashcard generation sessions
-- =============================================================================

create table if not exists public.flashcard_generations (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar not null,
  generated_count integer not null,
  accepted_unedited_count integer,
  source_text_hash varchar not null,
  source_text_length integer not null check (source_text_length between 1000 and 10000),
  generation_duration integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.flashcard_generations is 'logs ai generation sessions for analytics and success metrics';
comment on column public.flashcard_generations.model is 'name of the ai model used for generation';
comment on column public.flashcard_generations.generated_count is 'total number of flashcards generated by ai';
comment on column public.flashcard_generations.accepted_unedited_count is 'number of flashcards accepted without editing';
comment on column public.flashcard_generations.source_text_hash is 'hash of source text to detect duplicate generation requests';
comment on column public.flashcard_generations.source_text_length is 'length of source text in characters (1000-10000)';
comment on column public.flashcard_generations.generation_duration is 'time taken for ai generation in milliseconds';

-- RLS disabled for development
-- alter table public.flashcard_generations enable row level security;

-- create index on user_id for improved query performance
create index idx_generations_user_id on public.flashcard_generations(user_id);

-- create index on source_text_hash for duplicate detection
create index idx_generations_source_hash on public.flashcard_generations(source_text_hash);

-- =============================================================================
-- table: flashcards
-- purpose: stores user flashcards (manually created or ai-generated)
-- =============================================================================

create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  front varchar(200) not null check (char_length(front) <= 200),
  back varchar(500) not null check (char_length(back) <= 500),
  source varchar(50) not null check (source in ('ai-full', 'ai-edited', 'manual')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  generation_id bigint references public.flashcard_generations(id) on delete set null
);

comment on table public.flashcards is 'stores user flashcards created manually or via ai generation';
comment on column public.flashcards.front is 'front side of flashcard, max 200 characters';
comment on column public.flashcards.back is 'back side of flashcard, max 500 characters';
comment on column public.flashcards.source is 'origin of flashcard: ai-full (accepted as-is), ai-edited (modified after generation), manual (created by user)';
comment on column public.flashcards.generation_id is 'optional reference to the generation session that created this flashcard';

-- RLS disabled for development
-- alter table public.flashcards enable row level security;

-- create index on user_id for improved query performance
create index idx_flashcards_user_id on public.flashcards(user_id);

-- create index on generation_id for improved query performance when filtering by generation
create index idx_flashcards_generation_id on public.flashcards(generation_id);

-- =============================================================================
-- table: generation_error_logs
-- purpose: logs ai generation errors for debugging and analytics
-- =============================================================================

create table if not exists public.generation_error_logs (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar not null,
  source_text_hash varchar not null,
  source_text_length integer not null check (source_text_length between 1000 and 10000),
  error_code varchar(100) not null,
  error_message text not null,
  created_at timestamptz not null default now()
);

comment on table public.generation_error_logs is 'logs errors during ai generation for debugging and monitoring';
comment on column public.generation_error_logs.model is 'name of the ai model that failed';
comment on column public.generation_error_logs.source_text_hash is 'hash of source text that caused the error';
comment on column public.generation_error_logs.source_text_length is 'length of source text in characters (1000-10000)';
comment on column public.generation_error_logs.error_code is 'error code returned by the ai service';
comment on column public.generation_error_logs.error_message is 'detailed error message for debugging';

-- RLS disabled for development
-- alter table public.generation_error_logs enable row level security;

-- create index on user_id for improved query performance
create index idx_error_logs_user_id on public.generation_error_logs(user_id);

-- =============================================================================
-- trigger: auto-update updated_at timestamp on flashcards
-- purpose: automatically update the updated_at column when a flashcard is modified
-- =============================================================================

-- create function to update updated_at timestamp
create or replace function public.update_flashcards_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.update_flashcards_updated_at is 'trigger function to automatically update updated_at timestamp';

-- create trigger on flashcards table
create trigger trigger_update_flashcards_updated_at
  before update on public.flashcards
  for each row
  execute function public.update_flashcards_updated_at();

comment on trigger trigger_update_flashcards_updated_at on public.flashcards is 'automatically updates updated_at column on flashcard modifications';

-- =============================================================================
-- trigger: auto-update updated_at timestamp on flashcard_generations
-- purpose: automatically update the updated_at column when a generation record is modified
-- =============================================================================

-- create function to update updated_at timestamp for generations
create or replace function public.update_generations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.update_generations_updated_at is 'trigger function to automatically update updated_at timestamp for generations';

-- create trigger on flashcard_generations table
create trigger trigger_update_generations_updated_at
  before update on public.flashcard_generations
  for each row
  execute function public.update_generations_updated_at();

comment on trigger trigger_update_generations_updated_at on public.flashcard_generations is 'automatically updates updated_at column on generation record modifications';
